mijnZorgRooster/Controllers/RollenController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mijnZorgRooster.DAL;
using mijnZorgRooster.Models;
using mijnZorgRooster.DAL.Entities;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using mijnZorgRooster.DAL.Repositories;

namespace mijnZorgRooster.Controllers
{
    public class RollenController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IRolRepository _rolRepository;
            
        public RollenController(IUnitOfWork unitOfWork, IRolRepository rolRepository)
        {
            _unitOfWork = unitOfWork;
            _rolRepository = rolRepository;
        }

        // GET: Rollen
        public async Task<IActionResult> Index()
        {
            return View(await _rolRepository.GetAsync());
        }

        // GET: Rollen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            RolDTO rolDTO = null;
    
            if (id.HasValue)
            {
                rolDTO = await _rolRepository.GetByIdAsync(id.Value);
            }
            else
            {
                return NotFound();
            }

            return View(rolDTO);
        }

        // GET: Rol/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rol/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RolID,Naam")] Rol rol)
        {
            if (ModelState.IsValid)
            {
                _rolRepository.Insert(rol);
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rol);
        }

        //// GET: Rol/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            RolDTO rolDTO = await _rolRepository.GetByIdAsync(id.Value);

            if (rolDTO == null)
            {
                return NotFound();
            }

            return View(rolDTO);
        }

        //// POST: Rol/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RolID,Naam")] Rol rol)
        {
            if (id != rol.RolID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _rolRepository.Update(rol);
                    await _unitOfWork.SaveAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await RolExists(rol.RolID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            RolDTO rolDto = new RolDTO
            {
                RolID = rol.RolID,
                Naam = rol.Naam
            };

            return View(rolDto);
        }

        //// GET: Rol/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            RolDTO rolDTO = null;
            if (id.HasValue)
            {
                rolDTO = await _rolRepository.GetByIdAsync(id.Value);
            }
            else
            {
                return NotFound();
            }

            if (rolDTO == null)
            {
                return NotFound();
            }

            return View(rolDTO);
        }

        // POST: Rol/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _rolRepository.Delete(id);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> RolExists(int id)
        {
            var res = await _rolRepository.GetAsync();
            return res.Any(m => m.RolID == id);
        }
    }
}

mijnZorgRooster/Controllers/RoosterController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mijnZorgRooster.Models;
using mijnZorgRooster.DAL.Entities;
using mijnZorgRooster.DAL;
using mijnZorgRooster.Services;
using mijnZorgRooster.DAL.Repositories;

namespace mijnZorgRooster.Controllers
{
    public class RoosterController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        private readonly IRoosterRepository _roosterRepository;
        private readonly IDienstRepository _dienstRepository;

		public RoosterController(IUnitOfWork unitOfWork, IRoosterRepository roosterRepository, IDienstRepository dienstRepository)
		{
			_unitOfWork = unitOfWork;
            _roosterRepository = roosterRepository;
            _dienstRepository = dienstRepository;
		}

		// GET: Rooster
		public async Task<IActionResult> Index()
		{
			return View(await _roosterRepository.GetAsync());
		}

		// GET: Rooster/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			RoosterDTO roosterDTO = null;

			if (id.HasValue)
			{
                roosterDTO = await _roosterRepository.GetByIdAsync(id.Value);
			}
			else
			{
				return NotFound();
			}

			return View(roosterDTO);
		}

		// GET: Rooster/Create
		public IActionResult Create()
		{
            TempData["MinInvoerJaar"] = DateTime.UtcNow.Year;
            return View();
		}

		// POST: Rooster/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("RoosterID,Jaar,Maand")] Rooster rooster)
		{
			if (ModelState.IsValid)
			{
				rooster.IsGevalideerd = false;
				_roosterRepository.Insert(rooster);
				await _unitOfWork.SaveAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(rooster);
		}

		// GET: Rooster/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			RoosterMetDienstProfielenDTO roosterDTO = await _roosterRepository.GetRoosterMetDienstProfielenDto(id.Value);

			if (roosterDTO == null)
			{
				return NotFound();
			}

            TempData["MinInvoerJaar"] = DateTime.UtcNow.Year;

			return View(roosterDTO);
		}

		// POST: Rooster/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("RoosterID,AanmaakDatum,Jaar,Maand,IsGevalideerd")] Rooster rooster, List<int> selectedDienstProfielen)
		{
			if (id != rooster.RoosterID)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
                    _roosterRepository.Update(rooster);

                    var oudRooster = await _roosterRepository.GetRoosterMetDienstProfielenDto(id);
                    var lijstMetRoosterDienstProfielIds = oudRooster.RoosterDienstProfielen.Select(rdp => rdp.DienstProfielId).Distinct().ToList();

                    if (!lijstMetRoosterDienstProfielIds.SequenceEqual(selectedDienstProfielen)) //check of de dienstprofielen van een rooster zijn veranderd
                    {
                        await _roosterRepository.UpdateRoosterDienstProfielen(id, selectedDienstProfielen);

                        //Nu moeten we diensten die aan het rooster hangen nog updaten
                        List<Dienst> nieuweDiensten = _dienstRepository.GenereerDiensten(id, selectedDienstProfielen);
                        rooster.Diensten = nieuweDiensten;
                        _roosterRepository.Update(rooster);
                    }

                    _unitOfWork.Save();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!await RoosterExists(rooster.RoosterID))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(rooster);
		}

		// GET: Rooster/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			RoosterDTO roosterDTO = null;
			if (id.HasValue)
			{
                roosterDTO = await _roosterRepository.GetByIdAsync(id.Value);
			}
			else
			{
				return NotFound();
			}

			if (roosterDTO == null)
			{
				return NotFound();
			}

			return View(roosterDTO);
		}

		// POST: Rooster/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(int id)
		{
			_roosterRepository.Delete(id);
			_unitOfWork.Save();
			return RedirectToAction(nameof(Index));
		}

		private async Task<bool> RoosterExists(int id)
		{
			var res = await _roosterRepository.GetAsync();
			return res.Any(r => r.RoosterID == id);
		}
	}
}

mijnZorgRooster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mijnZorgRooster</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Rooster" asp-action="" class="navbar-brand">mijnZorgRooster</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Over</a></li>
                    <li><a asp-area="" asp-controller="Medewerkers" asp-action="">Medewerkers</a></li>
                    <li><a asp-area="" asp-controller="Rooster" asp-action="">Roosters</a></li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stamgegevens <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Rollen" asp-action="">Rollen</a></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="DienstProfiel" asp-action="">Dienstprofielen</a></li>
                        </ul>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - mijnZorgRooster</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>