mijnZorgRooster/Controllers/DienstController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mijnZorgRooster.Models;
using mijnZorgRooster.DAL.Entities;
using mijnZorgRooster.DAL;
using mijnZorgRooster.Services;
using mijnZorgRooster.DAL.Repositories;

namespace mijnZorgRooster.Controllers
{
	public class DienstController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        private readonly IDienstRepository _dienstRepository;

		public DienstController(IUnitOfWork unitOfWork, IDienstRepository dienstRepository)
		{
			_unitOfWork = unitOfWork;
            _dienstRepository = dienstRepository;
		}

		// GET: Dienst
		public async Task<IActionResult> Index()
		{
    		return View(await _dienstRepository.GetAsync());
		}

        public async Task<IActionResult> Details(int? id)
        {
            DienstDTO dienstDTO = null;

            if (id.HasValue)
            {
                dienstDTO = await _dienstRepository.GetByIdAsync(id.Value);
            }
            else
            {
                return NotFound();
            }

            return View(dienstDTO);
        }

	}
}

mijnZorgRooster/Controllers/RoosterController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mijnZorgRooster.Models;
using mijnZorgRooster.DAL.Entities;
using mijnZorgRooster.DAL;
using mijnZorgRooster.Services;
using mijnZorgRooster.DAL.Repositories;

namespace mijnZorgRooster.Controllers
{
    public class RoosterController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        private readonly IRoosterRepository _roosterRepository;
        private readonly IDienstRepository _dienstRepository;

		public RoosterController(IUnitOfWork unitOfWork, IRoosterRepository roosterRepository, IDienstRepository dienstRepository)
		{
			_unitOfWork = unitOfWork;
            _roosterRepository = roosterRepository;
            _dienstRepository = dienstRepository;
		}

		// GET: Rooster
		public async Task<IActionResult> Index()
		{
			return View(await _roosterRepository.GetAsync());
		}

		// GET: Rooster/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			RoosterDTO roosterDTO = null;

			if (id.HasValue)
			{
                roosterDTO = await _roosterRepository.GetByIdAsync(id.Value);
			}
			else
			{
				return NotFound();
			}

			return View(roosterDTO);
		}

		// GET: Rooster/Create
		public IActionResult Create()
		{
            TempData["MinInvoerJaar"] = DateTime.UtcNow.Year;
            return View();
		}

		// POST: Rooster/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("RoosterID,Jaar,Maand")] Rooster rooster)
		{
			if (ModelState.IsValid)
			{
				rooster.IsGevalideerd = false;
				_roosterRepository.Insert(rooster);
				await _unitOfWork.SaveAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(rooster);
		}

		// GET: Rooster/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			RoosterMetDienstProfielenDTO roosterDTO = await _roosterRepository.GetRoosterMetDienstProfielenDto(id.Value);

			if (roosterDTO == null)
			{
				return NotFound();
			}

            TempData["MinInvoerJaar"] = DateTime.UtcNow.Year;

			return View(roosterDTO);
		}

		// POST: Rooster/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("RoosterID,AanmaakDatum,Jaar,Maand,IsGevalideerd")] Rooster rooster, List<int> selectedDienstProfielen)
		{
			if (id != rooster.RoosterID)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
                    _roosterRepository.Update(rooster);

                    var oudRooster = await _roosterRepository.GetRoosterMetDienstProfielenDto(id);
                    var lijstMetRoosterDienstProfielIds = oudRooster.RoosterDienstProfielen.Select(rdp => rdp.DienstProfielId).Distinct().ToList();

                    if (!lijstMetRoosterDienstProfielIds.SequenceEqual(selectedDienstProfielen)) //check of de dienstprofielen van een rooster zijn veranderd
                    {
                        await _roosterRepository.UpdateRoosterDienstProfielen(id, selectedDienstProfielen);

                        //Nu moeten we diensten die aan het rooster hangen nog updaten
                        List<Dienst> nieuweDiensten = _dienstRepository.GenereerDiensten(id, selectedDienstProfielen);
                        rooster.Diensten = nieuweDiensten;
                        _roosterRepository.Update(rooster);
                    }

                    _unitOfWork.Save();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!await RoosterExists(rooster.RoosterID))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(rooster);
		}

		// GET: Rooster/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			RoosterDTO roosterDTO = null;
			if (id.HasValue)
			{
                roosterDTO = await _roosterRepository.GetByIdAsync(id.Value);
			}
			else
			{
				return NotFound();
			}

			if (roosterDTO == null)
			{
				return NotFound();
			}

			return View(roosterDTO);
		}

		// POST: Rooster/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(int id)
		{
			_roosterRepository.Delete(id);
			_unitOfWork.Save();
			return RedirectToAction(nameof(Index));
		}

		private async Task<bool> RoosterExists(int id)
		{
			var res = await _roosterRepository.GetAsync();
			return res.Any(r => r.RoosterID == id);
		}
	}
}

mijnZorgRooster/Views/Rooster/Create.cshtml
@model mijnZorgRooster.DAL.Entities.Rooster
@{
	ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Rooster</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Jaar" class="control-label"></label>
				<input asp-for="Jaar" class="form-control" value=@TempData["MinInvoerJaar"] min=@TempData["MinInvoerJaar"] />
				<span asp-validation-for="Jaar" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Maand" class="control-label"></label>
				<input asp-for="Maand" class="form-control" min="1" max="12" />
				<span asp-validation-for="Maand" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mijnZorgRooster/Views/Rooster/Delete.cshtml
@model mijnZorgRooster.Models.RoosterDTO

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
	<h4>Rooster</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Jaar)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Jaar)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Maand)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Maand)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.AanmaakDatum)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.AanmaakDatum)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.WijzigingsDatum)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.WijzigingsDatum)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.IsGevalideerd)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.IsGevalideerd)
		</dd>
	</dl>

	<form asp-action="Delete">
		<input type="hidden" asp-for="RoosterID" />
		<input type="submit" value="Delete" class="btn btn-default" /> |
		<a asp-action="Index">Back to List</a>
	</form>
</div>

mijnZorgRooster/Views/Rooster/Details.cshtml
@model mijnZorgRooster.Models.RoosterDTO

@{
	ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
	<h4>Rooster</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Jaar)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Jaar)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Maand)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Maand)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.StartDatum)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.StartDatum)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.EindDatum)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.EindDatum)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.AantalDagen)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.AantalDagen)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.AanmaakDatum)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.AanmaakDatum)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.WijzigingsDatum)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.WijzigingsDatum)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.IsGevalideerd)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.IsGevalideerd)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model.RoosterID">Edit</a> |
	<a asp-action="Index">Back to List</a>
</div>
<div>
    @if (Model.Diensten != null)
    {
        <h3>Diensten behorende bij het rooster</h3>
        <table class="table">
            <tr>
                <th></th>
                <th>Datum</th>
                <th>Begintijd</th>
                <th>Eindtijd</th>
                <th>Beschrijving</th>
                <th>Minimale bezetting</th>
            </tr>

            @foreach (var item in Model.Diensten)
            {
                string selectedRow = "";
                if (item.DienstID == ViewBag.DienstID)
                {
                    selectedRow = "success";
                }
            <tr class="@selectedRow">
                <td>
                    <a asp-action="Details" asp-controller="Dienst" asp-route-id="@item.DienstID">Select</a>
                </td>
                <td>
                    @item.Datum
                </td>
                <td>
                    @item.Begintijd
                </td>
                <td>
                    @item.Eindtijd
                </td>
                <td>
                    @item.Beschrijving
                </td>
                <td>
                    @item.MinimaleBezetting
                </td>
            </tr>
            }

        </table>
    }
</div>

mijnZorgRooster/Views/Rooster/Edit.cshtml
@model mijnZorgRooster.Models.RoosterMetDienstProfielenDTO

@{
	ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Rooster</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="RoosterID" />
			<input type="hidden" asp-for="AanmaakDatum" />
			<div class="form-group">
				<label asp-for="Jaar" class="control-label"></label>
				<input asp-for="Jaar" class="form-control" min=@TempData["MinInvoerJaar"] />
				<span asp-validation-for="Jaar" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Maand" class="control-label"></label>
				<input asp-for="Maand" class="form-control" min="1" max="12" />
				<span asp-validation-for="Maand" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="IsGevalideerd" class="control-label"></label>
				<input asp-for="IsGevalideerd" class="form-control" />
				<span asp-validation-for="IsGevalideerd" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="SelectedDienstProfielen" class="control-label"></label>
				<select asp-for="SelectedDienstProfielen" asp-items="Model.DienstProfielOptions" class="form-control"></select>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-default" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mijnZorgRooster/Views/Rooster/Index.cshtml
@model IEnumerable<mijnZorgRooster.Models.RoosterDTO>

@{
	ViewData["Title"] = "Index";
}

<h2>Overzicht roosters</h2>

<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table" id="sortableTable">
	<thead>
		<tr>
			<th onclick="sortTable(0)">
				@Html.DisplayNameFor(model => model.Jaar)
			</th>
			<th onclick="sortTable(1)">
				@Html.DisplayNameFor(model => model.Maand)
			</th>
			<th onclick="sortTable(2)">
				@Html.DisplayNameFor(model => model.AanmaakDatum)
			</th>
			<th onclick="sortTable(3)">
				@Html.DisplayNameFor(model => model.WijzigingsDatum)
			</th>
			<th onclick="sortTable(4)">
				@Html.DisplayNameFor(model => model.IsGevalideerd)
			</th>
            <th onclick="sortTable(5)">
                @Html.DisplayNameFor(model => model.AantalDienstProfielen)
            </th>
            <th onclick="sortTable(6)">
                @Html.DisplayNameFor(model => model.AantalDiensten)
            </th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Jaar)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Maand)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.AanmaakDatum)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.WijzigingsDatum)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.IsGevalideerd)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.AantalDienstProfielen)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.AantalDiensten)
			</td>
			<td>
				<a asp-action="Edit" asp-route-id="@item.RoosterID">Edit</a> |
				<a asp-action="Details" asp-route-id="@item.RoosterID">Details</a> |
				<a asp-action="Delete" asp-route-id="@item.RoosterID">Delete</a>
			</td>
		</tr>
		}
	</tbody>
</table>